gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge
permalink:        /:title/
include:          ["_pages"]

title:            'Lukáš Bednařík'
# description:      'Praktiky, kultury a metodiky vývoje software. Baví mě optimalizovat, hledat souvislosti.'
# description:      'No Scrum bullshit ...ale praktiky a fungující proces.'
description:      'No Scrum bullshit ...ale spokojení lidé a kvalitní produkt.'
url:              'http://lukasbednarik.cz'
baseurl:          '/'

author:
  name:           'Lukáš Bednařík'
  url:            '#'

paginate:         5
future:           false
