# Lukáš Bednařík
# Theme based on Sera template

exclude: ["node_modules", "Gemfile", "README.md", "notes"]
url: 'https://lukasbednarik.cz'
permalink:        /:title/
include:          ["_pages"]
google-analytics: true
excerpt_separator: <!--more-->
future: false
show_drafts: false
#highlighter: rouge
sass:
    sass_dir: css
    style: compressed

author:
  name:           'Lukáš Bednařík'
  email:          'lukas@lukasbednarik.cz'
  phone:          '+420 723 759 530'
  ic:             '75488931'
  city:           'Brno'
  misto-podnikani: '77900 Olomouc, Slunečná 509/7'
description:      'Technický Agilní kouč. Baví mě Scrum, práce s týmem a technické praktiky.'

####################################
###########   Plugins    ###########
####################################

collections:
  tag:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: lukasbednarikcz
  card: summary
social:
  name: Lukáš Bednařík
  links:
    - https://twitter.com/lukasbednarikcz
    - https://www.facebook.com/lukasbednarikcz
    - https://www.linkedin.com/in/lukasbednarik
    - https://github.com/lukasbednarik

#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

lang: cs-CZ
title: Lukáš Bednařík
headter-tagline: Lukáš Bednařík
header-title: Technický Agilní kouč

####################################
######  Global Social Links   ######
####################################
linkedin: 'https://www.linkedin.com/company/lukasbednarikcz/'
facebook: 'https://www.facebook.com/lukasbednarikcz'
twitter: 'https://twitter.com/lukasbednarikcz'
github: 'https://github.com/lukasbednarik'
stackoverflow: 'https://stackoverflow.com/users/4734434/luk%C3%A1%C5%A1-bedna%C5%99%C3%ADk'

#########################
######   Widgets   ######
#########################
about-widget:
  author-avatar: lukas-bednarik.jpg
  author-name: Lukáš Bednařík
  author-tagline: Technický Agilní kouč
  author-info: Baví mě Scrum, práce s týmem a technické praktiky.
  author-social-links:
    linkedin: 'https://cz.linkedin.com/in/lukasbednarik'
    facebook: 'https://www.facebook.com/lukasbednarikcz'
    twitter: 'https://twitter.com/lukasbednarikcz'
    github: 'https://github.com/lukasbednarik'
    stackoverflow: 'https://stackoverflow.com/users/4734434/luk%C3%A1%C5%A1-bedna%C5%99%C3%ADk'

#####################################
#############   Bio    #############
#####################################
about-title: Lukáš Bednařík
about-description: Od roku 2014 vyvíjím software pro firmy. Pracoval jsem jako
  Scrum Master, zaváděl jsem Scrum jako Agilní kouč.
  Dnes vedu workshopy, konzultuji a opět... vyvíjím software.

#####################################
#############  Služby  ##############
#####################################
features-title: Služby
features-description:
  Máte v backlogu srovnatelný počet bugů a features?
  Trvá vám několik měsíců, než se do týmu zaučí noví lidé? Odhalujete chyby až při ručním testování?
  Gratuluji. Píšete legacy kód. A řešení? Řešení se jmenuje technické koučování.
  Tím se zabývám.
features:
- title: Technické praktiky
  description: Čistý kód napsaný rychle, efektivně i s testy. Můžete to mít všechno.
    To vám na workshopu ukážeme. Jaký je háček? Vývojáři se to musí naučit.
  icon: pe-7s-config
  link: Chci vědět víc!
  link-url: /workshop-technicke-praktiky-ve-scrumu/
- title: Coding Dojo
  description: TDD je zcela jiný způsob přemýšlení o kódu. Zlepšíte design, testování,
    udržitelnost kódu. Zlepšíte spolupráci v týmu.
  icon: pe-7s-mouse
  link: Chci to!
  link-url: /workshop-coding-dojo/
- title: Konzultace
  description: Chcete workshop na míru, diskuze o konkrétních tématech ve vaší organizaci
    nebo feedback?
  icon: pe-7s-users
  link: Možná. Pojďme na kafe!
  link-url: /konzultace/

#####################################
##########  S čím pomáhám  ##########
#####################################
core-title: Co umím?
core-description: Co umím, dělám sám. Co neumím, přenechávám kolegům (a kontaktů mám spousty).

core-features-left:
- name: Metodiky
  description: Pomohu s metodikami jako je Scrum, Kanban nebo XP.
  icon: pe-7s-target
- name: Práce s týmem
  description: Chcete vysoce výkonný tým? Nemožné dělám na počkání.
  icon: pe-7s-graph1
- name: Technické best practices
  description: Stovky bugů jsou pasé. Pojďme dělat software tak, jak se to má.
  icon: pe-7s-like2
- name: Starý kód, nové triky
  description: Zrychlíme úpravy v legacy kódu. A nezapotíme se.
  icon: pe-7s-monitor
core-features-right:
- name: Feedback
  description: Dám feedback na technologie, Scrum nebo Scrum Mastera.
  icon: pe-7s-refresh
- name: Škáluji metodiky
  description: Ve spolupráci s dalšími kouči škáluji technologie a metodiku.
  icon: pe-7s-loop
- name: Neumím zázraky
  description: Některé věci chtějí čas. Zvyky lidí za den nezměníme.
  icon: pe-7s-magic-wand
- name: Přijedu kamkoliv
  description: Rád za vámi přijedu kdekoli po ČR. Cestu neplatíte.
  icon: pe-7s-map-2


#####################################
########### Doporučení ##############
#####################################
testimonials-title: Doporučení
testimonials-description: Reference? Je jich málo? Inu, stále nejsem full-time freelancer.
testimonials:
- name: Jan Brada
  url: https://www.ipex.cz/
  url-text: Scrum Master, IPEX
  avatar: jan-brada.jpg
  cite: '[workshop] ...posbírané velmi zajímavé střípky ze světa vývojářů. Výstižně,
    stručně a trefně zachycené ve slajdech. Fakt DOST dobrý.'
  logo-img: ipex-logo.png
- name: Hana Jadavan
  url: https://www.avast.com
  url-text: Scrum Master, Avast
  avatar: hana-jadavan.jpg
  cite: '[workshop] Lukáš dokázal vše velmi srozumitelně, trpělivě vysvětlit a celý
    workshop měl příjemnou dynamiku... Po skončení workshopu jsme nejen
    dokázali prakticky použít všechny nově nabyté znalosti, ale tým se
    cítil motivovaný v tomto způsobu práce i nadále pokračovat.'
  logo-img: avast-logo.png

#####################################
############   Kontakt   ############
#####################################
contact-title: Napište mi
contact-description: Sejděme se na kafe. Rád vás poznám, i kdybychom se spolu
  nerozhodli spolupracovat.
