# Lukáš Bednařík
# Theme based on Sera template

exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "notes"]
url: 'https://lukasbednarik.cz'
permalink:        /:title/
include:          ["_pages"]
google-analytics: true
excerpt_separator: <!--more-->
#highlighter: rouge

author:
  name:           'Lukáš Bednařík'
  email:          'lukas@lukasbednarik.cz'
  phone:          '+420 723 759 530'
  ic:             '75488931'
  city:           'Brno'
  misto-podnikani: '77900 Olomouc, Staškova 569/15'
description:      'Technický Agilní kouč. Scrum, tým a technické praktiky.'

####################################
###########   Plugins    ###########
####################################

collections:
  tag:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Plugin configs
paginate: 10
paginate_path: '/blog/page:num'

twitter:
  username: lukasbednarikcz
  card: summary
social:
  name: Lukáš Bednařík
  links:
    - https://twitter.com/lukasbednarikcz
    - https://www.facebook.com/lukasbednarikcz
    - https://www.linkedin.com/in/lukasbednarik
    - https://github.com/lukasbednarik

#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################

lang: cs-CZ
title: Lukáš Bednařík
headter-tagline: Lukáš Bednařík
header-title: Technický Agilní kouč

####################################
######  Global Social Links   ######
####################################
linkedin: 'https://www.linkedin.com/company/lukasbednarikcz/'
facebook: 'https://www.facebook.com/lukasbednarikcz'
twitter: 'https://twitter.com/lukasbednarikcz'
github: 'https://github.com/lukasbednarik'
stackoverflow: 'https://stackoverflow.com/users/4734434/luk%C3%A1%C5%A1-bedna%C5%99%C3%ADk'

#########################
######   Widgets   ######
#########################
about-widget:
  author-avatar: lukas-bednarik.jpg
  author-name: Lukáš Bednařík
  author-tagline: Technický Agilní kouč
  author-info: Scrum, tým a technické praktiky. Stovky bugů jsou minulostí.
  author-social-links:
    linkedin: 'https://cz.linkedin.com/in/lukasbednarik'
    facebook: 'https://www.facebook.com/lukasbednarikcz'
    twitter: 'https://twitter.com/lukasbednarikcz'
    github: 'https://github.com/lukasbednarik'
    stackoverflow: 'https://stackoverflow.com/users/4734434/luk%C3%A1%C5%A1-bedna%C5%99%C3%ADk'

#####################################
#############   Bio    #############
#####################################
about-title: Lukáš Bednařík
about-description: Baví mě Scrum, práce s týmem a technické praktiky.
  Mám zkušenosti jako vývojář, Scrum Master i Agilní Kouč.
  Pomohu vám nastartovat Scrum a cyklus neustálého učení a inovací.
  Společně se vypořádáme s technickým dluhem a nasedneme na vlak moderních technologií.
  <a href="/o-mne/">A co se letos mi povedlo?</a>

#####################################
#############  Služby  ##############
#####################################
features-title: Služby
features-description:
  Své zákazníky učím tomu, na co by si jinak delší cestou přišli sami.
  Šetřím peníze. Akceleruji učení. Provedu vás cestou, na které jsem již byl.
features:
- title: Technická Agilita
  description: Bez správných technických praktik ve vývoji je každý Scrum
    nejvýše na polovině svého potenciálu.
    Tento workshop posune váš tým vývojářů na další úroveň. Zaručeno.
  icon: pe-7s-study
  link: Chci vědět víc!
  link-url: /workshop-technicka-agilita/
- title: Workshop na míru
  description: Přednášel jsem a vedl workshopy na různá témata. Pojďme společně vybrat
    obsah, který je pro vaši situaci relevantní.
  icon: pe-7s-plugin
  link: Jaká mohou být témata workshopů a kolik to stojí?
  link-url: /workshop-na-miru/
- title: Konzultace
  description: Workshop je pro vás příliš obecný a chcete se bavit o konkrétních
    problémech ve vašem kódu nebo vašem týmu?
  icon: pe-7s-users
  link: Možná. Pojďme na kafe!
  link-url: /konzultace/

#####################################
##########  S čím pomáhám  ##########
#####################################
core-title: Co umím?
core-description: Mám široké znalosti z vývoje, vyznám se v současných technologických trendech,
  umím pracovat s týmem a frameworkem Scrum.

core-features-left:
- name: Metodiky
  description: Pomohu s metodikami jako je Scrum, Kanban nebo XP.
  icon: pe-7s-target
- name: Práce s týmem
  description: Chcete vysoce výkonný tým? Mám rád zdravou výzvu.
  icon: pe-7s-rocket
- name: Technické best practices
  description: Stovky bugů jsou pasé. Pojďme dělat software tak, jak se to má.
  icon: pe-7s-like2
- name: Starý kód, nové triky
  description: Zrychlíme úpravy v legacy kódu. A nezapotíme se.
  icon: pe-7s-mouse
core-features-right:
- name: Feedback
  description: Dám feedback na Scrum, Scrum Mastera nebo technologie.
  icon: pe-7s-refresh
- name: Škáluji metodiky
  description: S Agile Navigators s.r.o. škáluji Scrum a technologie.
  icon: pe-7s-loop
- name: Neumím zázraky
  description: Některé věci chtějí čas. Zvyky lidí za den nezměníme.
  icon: pe-7s-magic-wand
- name: Přijedu kamkoliv
  description: Rád za vámi přijedu kdekoli po ČR. Cestu neplatíte.
  icon: pe-7s-map-2


#####################################
########### Doporučení ##############
#####################################
testimonials-title: Doporučení
testimonials-description: Reference? Je jich málo? Inu, stále nejsem full-time freelancer.
testimonials:
- name: Jan Brada
  url: https://www.ipex.cz/
  url-text: Scrum Master, IPEX
  avatar: jan-brada.jpg
  cite: '[workshop] ...posbírané velmi zajímavé střípky ze světa vývojářů. Výstižně,
    stručně a trefně zachycené ve slajdech. Fakt DOST dobrý.'
  logo-img: ipex-logo.png
- name: Hana Jadavan
  url: https://www.avast.com
  url-text: Scrum Master, Avast
  avatar: hana-jadavan.jpg
  cite: '[workshop] Lukáš dokázal vše velmi srozumitelně, trpělivě vysvětlit a celý
    workshop měl příjemnou dynamiku... Po skončení workshopu jsme nejen
    dokázali prakticky použít všechny nově nabyté znalosti, ale tým se
    cítil motivovaný v tomto způsobu práce i nadále pokračovat.'
  logo-img: avast-logo.png

#####################################
############# Blog ##################
#####################################
blog-title: Blog
blog-description: Od začátku roku 2017 píšu blog. Marketing? Ne, baví mě to!

#####################################
############   Kontakt   ############
#####################################
contact-title: Napište mi
contact-description: Sejděme se - jen tak nezávazně - na kafe. Napište mi.
