gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge
permalink:        /:title/
include:          ["_pages"]

title:            'Lukáš Bednařík'
tagline:          'blog'
# description:      'Rebelský vůdce týmu. Praktiky, kultury, metodiky vývoje software.'
description:      'Vývoj software. Praktiky, kultury, metodiky. Baví mě optimalizovat, hledat souvislosti.'
url:              'http://lukasbednarik.cz'
baseurl:          '/'

author:
  name:           'Lukáš Bednařík'
  url:            '#'

paginate:         5
future:           false
