gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge
permalink:        /:title/
include: ["_pages"]

# Setup
title:            'title' #'Lukáš Bednařík'
tagline:          'blog'
description:      'some text' #'Agilní techniky, procesy, metodiky.<a href="#" target="_blank">Facebook</a>.'
url:              'http://lukasbednarik.cz'
baseurl:          '/'

author:
  name:           'Lukáš Bednařík'
  url:            '#'

paginate:         5
