plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-seo-tag

markdown:         kramdown
highlighter:      rouge
permalink:        /:title/
include:          ["_pages"]
url:              'https://lukasbednarik.cz'
baseurl:          '/'
paginate:         11
future:           false

title:            'Lukáš Bednařík'
author:
  name:           'Lukáš Bednařík'
  email:          'lukas@lukasbednarik.cz'
description:      'Technický Agilní kouč. Kvalitnější software rychleji.'
lang: cs_CZ
twitter:
  username: lukasbednarikcz
  card: summary
social:
  name: Lukáš Bednařík
  links:
    - https://twitter.com/lukasbednarikcz
    - https://www.facebook.com/lukasbednarikcz
    - https://www.linkedin.com/in/lukasbednarik
    - https://github.com/lukasbednarik
# logo
