plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge
permalink:        /:title/
include:          ["_pages"]
url:              'https://lukasbednarik.cz'
baseurl:          '/'
paginate:         11
future:           false

title:            'Lukáš Bednařík'
author:
  name:           'Lukáš Bednařík'
  email:          'lukas@lukasbednarik.cz'
#description:      'No Scrum bullshit ...ale spokojení lidé a kvalitní produkt.'
#description:      'Jsem technický kouč. Zabývám se efektivním vývojem softwaru.'
#description:      'Jsem technický kouč. Pomáhám týmům vyvíjet software rychleji a kvalitněji.'
description:      'Technický kouč. Kvalitnější software rychleji.'
seo:
  description:    'Pomáhám týmům vyvíjet software rychleji a kvalitněji.'
  keywords:       'firemní kultury,praktiky,metodiky,vývoj software,školení,extrémní programování,workshop,kanban'
